[package]
name = "sync-github"
version = "0.1.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
log = "0.4.7"
env_logger = "0.6.2"
rust_team_data = { git = "https://github.com/rust-lang/team" }
serde = { version = "1.0.94", features = ["derive"] }
failure = "0.1.5"
base64 = "0.10.1"
hyper-old-types = "0.11.0"
tempfile = "3.1.0"
serde_json = "1.0.40"
